### ISSUE TITLE
Missing Submit Button Loading Indicator

### ISSUE THREAD

**Issue by PasanSWijekoon** [PasanSWijekoon/UMeeChat-App-FrontEnd#14]
When submitting the form, there is no visual indication that the form is being submitted, which may cause users to click the submit button multiple times.

**Comment by david-solomon-henshaw** [comment]
@PasanSWijekoon can you assign me this issue also can you add hacktoberfest to all the issues so that it counts thanks

**Comment by PasanSWijekoon** [comment]
Ok Sure Do You have experience in react native with expo

**Comment by PasanSWijekoon** [comment]
Current code Use   const [isSubmitting, setIsSubmitting] = useState(false); // Track submission state

Usage It Prevent User From Continue Sumbit fetch to server

**Comment by david-solomon-henshaw** [comment]
@PasanSWijekoon Yes i do have experience with react native and expo also am i still assigned to the issue ?

**Comment by PasanSWijekoon** [comment]
yes

**Comment by david-solomon-henshaw** [comment]
@PasanSWijekoon alright boss on it
