### ISSUE TITLE
No Feedback on Image Upload Success/Failure

### ISSUE THREAD

**Issue by PasanSWijekoon** [PasanSWijekoon/UMeeChat-App-FrontEnd#15]
Users do not receive any feedback after selecting an image for the profile.

**Comment by david-solomon-henshaw** [comment]
@PasanSWijekoon  is this during the sign in stage ?

**Comment by david-solomon-henshaw** [comment]
![Screenshot 2024-10-11 at 10-17-10 umeechat](https://github.com/user-attachments/assets/52771fc8-5f2b-4a9f-ba04-088b50e32b0d)
